# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
#     env:
#       PORT: $PORT
#       MONGODB_URL: ${{MONGODB_URL}}
#       JWT_SECRET: $JWT_SECRET
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      #- run: npm run build --if-present
      - run: echo "---- $PORT ---- $JWT_SECRET ---- ${{env.MONGODB_URL}} ---- "
      - run: npm run test
      - run: npm run build
      - run: pm2 status
      - run: pm2 delete nikhil
      - run: pm2 start --name nikhil ./dist/src/app.js -i max
